kind: Service
apiVersion: v1
metadata:
  name: dev-cicdapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8181
    protocol: TCP
  selector:
    app: cicdapp
    env: dev