kind: Deployment
apiVersion: apps/v1
metadata:
  name: cicdapp-prod
spec:
  replicas: 2
  selector:
      matchLabels:
          app: cicdapp
          env: prod
  template:
    metadata:
      name: backend
      labels:
        app: cicdapp
        env: prod
    spec:
      containers:
      - name: cicdappcontainer
        image: gcr.io/southern-shard-265012/cicdapp:v.11
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8181
        ports:
        - name: cicdapp-prod
          containerPort: 8181